### ISSUE TITLE
namespace handling/removal

### ISSUE THREAD

**Issue by enziop** [enziop/mixamo_converter#1]
## Simple
just remove everything before first colon if there is one
## Advanced
- detect namespaces and display them in a tree structure
- delete, merge and rename namespaces

**Comment by gnuton** [comment]
Simple case is already handled.
The advanced one is not. Is this still issue still valid or can we close this issue?

**Comment by enziop** [comment]
we can close it, the advanced feature is basicly namespace support for blender in general but not at all needed for the mixamo converter
