### ISSUE TITLE
Batch convert doesn't quite work. Maybe an issue with Mixamo rig?

### ISSUE THREAD

**Issue by Atulin** [enziop/mixamo_converter#10]
![image](https://user-images.githubusercontent.com/11233299/31050270-cbf0b20c-a645-11e7-9fbe-5639ab2ec0af.png)

**Comment by enziop** [comment]
A new version of the script has just been released (1.0.3) including many fixes. Can you retry it?
If the error occurs again can you please post the error message here. You can get it by pulling down the top  info panel bar of the blender window, there you can mark the error message with right click and then copy it.
thank you

**Comment by Atulin** [comment]
Version 1.0.3
```
Traceback (most recent call last):
  File "C:\Users\Angius\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\__init__.py", line 231, in execute
    numfiles = mixamoconv.batch_hip_to_root(
AttributeError: module 'mixamo_converter-master.mixamoconv' has no attribute 'batch_hip_to_root'

location: <unknown location>:-1
```

**Comment by enziop** [comment]
I can't reproduce your problem on my side, did you install the addon like it is described in the readme?
and did you remove the old one before installing the new one?

**Comment by Atulin** [comment]
Yes and yes.

**Comment by gnuton** [comment]
Atulin, can you try again with the new version or can we close this bug report?

**Comment by Atulin** [comment]
No cigar, I'm afraid. It's a different error, however, so it's something.

```
Traceback (most recent call last):
  File "C:\Users\Angius\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\__init__.py", line 275, in execute
    ignore_leaf_bones =mixamo.ignore_leaf_bones)
TypeError: batch_hip_to_root() got an unexpected keyword argument 'b_unreal_bones'

location: <unknown location>:-1
```

**Comment by gnuton** [comment]
I will try to fix it this weekend if you tell me how to reproduce it. Show
me the options you use and a test file to try out.
Thanks

**Comment by Atulin** [comment]
Ah, I think I diagnosed the issue right now.

I had a stray fbx file in the output path. When I removed it, everything went without a hitch.

**Comment by gnuton** [comment]
can we close this issue then?

**Comment by Atulin** [comment]
Just wanted to note that the output files are in a `name..fbx` format, so you might want to track that dot down and remove it, but other than that - sure. The issue can be considered solved and closed.

**Comment by gnuton** [comment]
Double dot in the output filenames has been fixed in 
https://github.com/enziop/mixamo_converter/pull/20
