### ISSUE TITLE
flatten joints

### ISSUE THREAD

**Issue by gnuton** [enziop/mixamo_converter#11]
Hi,
I tried the latest version of this converter and the mesh gets flattened close to elbows during animations.
This issue is not visible if I import the FBX straight from mixamo.
Any idea on what's wrong?

![image](https://user-images.githubusercontent.com/576580/31311065-1e0b9ffe-abad-11e7-94c5-d1492e5a08b2.png)
Here is another model which shows the same problem between arm and forearm
![image](https://user-images.githubusercontent.com/576580/31311115-0e60a292-abae-11e7-9bd6-5bd69eba1f82.png)

Here is the problem shown in blender
![image](https://user-images.githubusercontent.com/576580/31311175-26f5fd60-abaf-11e7-9a0d-50ac0e862099.png)

**Comment by gnuton** [comment]
Looks like here is the solution to this issue
https://blender.stackexchange.com/questions/72355/fbx-vertex-weight-import-problem

**Comment by enziop** [comment]
Hi,
so if you directly import it to unreal without going through blender it looks right?
then there should be any right data in it somehow, i have no idea how this happens, but can you send me an unconverted file where this happens so i can test it?

**Comment by gnuton** [comment]
Hi,
Yes it looks right  if I import the FBX straight from mixamo.
It looks like this is a known mixamo bug. Blender guys do now want to have any workaround for it.
If I got it right unreal re-calculates the weights if those are broken or not there. Blender doesn't and set those to 0 and export them as 0. Unreal doesn't recalculates the weights if those are set.

You can read more about it here: https://developer.blender.org/T43992

FBX anim exported by mixamo converter 
![image](https://user-images.githubusercontent.com/576580/31315159-6ca0f682-ac1b-11e7-8a67-ba5e6e1f0691.png)

This is the same FBX imported straight from mixamo
![image](https://user-images.githubusercontent.com/576580/31315173-c795efca-ac1b-11e7-8bed-9efb1a36c0da.png)

Here are the FBX mixamo file and the one converted by this tool using blender.
[BUG.zip](https://github.com/enziop/mixamo_converter/files/1366732/BUG.zip)

**Comment by gnuton** [comment]
UPDATE:
Collada files exported by mixamo do not suffer of the invalid vertex weight.
Unfortunately this blender plugin doesn't support armature naming in the collada files.
#13 is tracking that issue, which can be used to workaround this issue.

**Comment by enziop** [comment]
So, i'm a bit busy at the moment, but i try to add collada support to the batch converter in the next few days.
Thanks for your namespace patch

**Comment by gnuton** [comment]
This evening I played a little bit with the importing settings of the collada files in blender.
If all the options are checked the final skeleton matches the one in the FBX.

![image](https://user-images.githubusercontent.com/576580/31520983-826e0cf0-afb0-11e7-9890-790de5413bf4.png)

**Comment by gnuton** [comment]
This evening I tested the new changes once again on a broader set of collada and fbx animations and this problem is not visible at all with collada.. So that's the way to go.
