### ISSUE TITLE
The plugin crashes when trying to batch convert old mixamo animations

### ISSUE THREAD

**Issue by gnuton** [enziop/mixamo_converter#12]
Mixamo converter crashes when converting old mixamo animations.
Here is the stacktrace

```
Traceback (most recent call last):
  File "C:\Users\BigGoliath\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\__init__.py", line 247, in execute
    ignore_leaf_bones = mixamo.ignore_leaf_bones)
  File "C:\Users\BigGoliath\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\mixamoconv.py", line 238, in batch_hip_to_root
    bpy.ops.import_scene.fbx(filepath=file.path, axis_forward='-Z', axis_up='Y', directory="", filter_glob="*.fbx", ui_tab='MAIN', use_manual_orientation=False, global_scale=1, bake_space_transform=False, use_custom_normals=True, use_image_search=True, use_alpha_decals=False, decal_offset=0, use_anim=True, anim_offset=1, use_custom_props=True, use_custom_props_enum_as_string=True, ignore_leaf_bones=ignore_leaf_bones, force_connect_children=False, automatic_bone_orientation=False, primary_bone_axis='Y', secondary_bone_axis='X', use_prepost_rot=True)
  File "R:\Steam\steamapps\common\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "R:\Steam\steamapps\common\Blender\2.79\scripts\addons\io_scene_fbx\__init__.py", line 234, in execute
    return import_fbx.load(self, context, **keywords)
  File "R:\Steam\steamapps\common\Blender\2.79\scripts\addons\io_scene_fbx\import_fbx.py", line 2843, in load
    _(); del _
  File "R:\Steam\steamapps\common\Blender\2.79\scripts\addons\io_scene_fbx\import_fbx.py", line 2841, in _
    blen_read_animations(fbx_tmpl_astack, fbx_tmpl_alayer, stacks, scene, settings.anim_offset)
  File "R:\Steam\steamapps\common\Blender\2.79\scripts\addons\io_scene_fbx\import_fbx.py", line 676, in blen_read_animations
    if id_data.type == 'MESH' and id_data.parent and id_data.parent.type == 'ARMATURE':
AttributeError: 'NoneType' object has no attribute 'type'

location: R:\Steam\steamapps\common\Blender\2.79\scripts\modules\bpy\ops.py:189
location: <unknown location>:-1
```
To reproduce the crash, please run batch conversion of a folder containing this FBX [wheelchair.zip](https://github.com/enziop/mixamo_converter/files/1367221/wheelchair.zip)

Solution:
Old Mixamo FBX looks fine in blender only if they are opened with "Automatic Bone Orientation" option enabled and leaf bones disabled.
![image](https://user-images.githubusercontent.com/576580/31321066-e67e03de-ac87-11e7-8006-f09bcf7b8974.png)

**Comment by gnuton** [comment]
I patched  mixamo_converter in my working copy, and I managed to read old mixamo animations.
The problem is that the skeleton of the converted file that I get out of this plugin is very far from the new mixamo skeleton.

**Comment by enziop** [comment]
@gnuton is this issue still valid? i tried batchconverting the wheelchair file and after conversion everything looks fine

**Comment by gnuton** [comment]
Hi enzio, i think we can close it for now.

**Comment by enziop** [comment]
@gnuton I am Planning to set Ignore Leaf Bones, and Automatic Bone Orientation to False as a default, as it does not make sense for most cases."Ignore Leaf Bones" only makes sense if the rig one is using was previously exported from blender with "Add Leaf Bones" to true
Automatic Bone Rotation does make sense for old animations but may cause unwanted offsets in restposes when using rigs from the autorigger or own custom rigs.
I think you hardcoded it once to be True, i added it as an option and now want to set it to False by default adding to the tooltip that it can be used when using old mixamo characters.
What do you mean?
