### ISSUE TITLE
Not a directory error

### ISSUE THREAD

**Issue by Dennisgreg** [enziop/mixamo_converter#25]
Hello ! 

First of, thanks a lot for this addon, it could really save me a lot of time! I followed the video tutorial but upon batch converting the T-Pose file I get this message in the console: 

```
Traceback (most recent call last):
  File "C:\Users\Denis Jr Clement\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\__init__.py", line 275, in execute
    ignore_leaf_bones =mixamo.ignore_leaf_bones)
  File "C:\Users\Denis Jr Clement\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\mixamoconv.py", line 321, in batch_hip_to_root
    for file in os.scandir(source_dir):
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\Denis Jr Clement\\Desktop\\Mixamo\\T-Pose.fbx'

location: <unknown location>:-1
```

Any idea what could cause this ? I am under the impression that the spaces in the User directory may be the cause but I don't want to format everything without being 100% sure. 

Thanks in advance for the help !

**Comment by gnuton** [comment]
Hi and thanks for reporting this issue. We will fix it. As for now when you choose a directory in batch mode, be sure there is no a file selected too. :)

**Comment by Dennisgreg** [comment]
@gnuton  Thanks for replying so quickly. Turns out I am a dumb f**k as I had a file selected when I tried to convert in batch mode.... tried again and everything works fine. Thanks again for this super useful addon and its support :)
