### ISSUE TITLE
Error: Traceback most recent call last 192 495 292

### ISSUE THREAD

**Issue by fpibbs** [enziop/mixamo_converter#29]
Hi, I have same error here: errors in line 292 and 425 of python script...using fbx. Using Blender 2.79b...now the plugin is completely useless...it could be a complete timesaver! Please fix!!! :)

 https://ibb.co/fZUT9S

**Comment by enziop** [comment]
nevermind, the image link seemed broken first
are you trying to do batch conversion or single conversion?
the error log looks like you pressed batch convert, did you select a proper input and output path for batch conversion?

**Comment by fpibbs** [comment]
Sure, I used Tpose fbx models direclty taken from Autodesk Character Creator, as is and pasted and redownloaded from Mixamo (as TPose not animated), then I tried a Mixamo animation both skinned and non skinned, so 4 cases in total...
 the full error code is...

Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\__init__.py", line 292, in execute
    ignore_leaf_bones = mixamo.ignore_leaf_bones)
  File "C:\Users\XXX\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\mixamoconv.py", line 357, in batch_hip_to_root
    for file in os.scandir(source_dir):
NotADirectoryError: [WinError 267] Nome di directory non valido: 'C:\\Users\\XXX\\Desktop\\Defeated_nonSKinned.fbx'

location: <unknown location>:-1

**Comment by fpibbs** [comment]
If I press single, it returns, cube is not an armature...that is logical, because following your youtube video, you used batch to prevent passing into blender 3d world outliner, but processing an external file...what am i doing wrongly?

**Comment by fpibbs** [comment]
I tried not indicating fbx but only folder, and I have same error...:(

 https://ibb.co/dYiRW7

**Comment by enziop** [comment]
can you show/past the last lines of the error again?

**Comment by enziop** [comment]
are there some files with no rigs in them? it looks like the armature/rig is not found in some file
you have to make a folder where you only put the rig animations that you want to convert and use it as source folder, if there are "unconvertable" files like for example ones with no rig it will fail on them

**Comment by fpibbs** [comment]
can you please send me a certain rigged file, one that is sure to work, to verify is not a problem of installation in blender or of the plugin, but comes from the models?

**Comment by enziop** [comment]
this is just the mixamo standard character with a walk on it
it works on my side
[Walking.fbx.zip](https://github.com/enziop/mixamo_converter/files/1987096/Walking.fbx.zip)

**Comment by fpibbs** [comment]
SOLVED using directly my models! :)
Worked like a charm: when you have a model in tpose from Autodesk character creator or fuse, you have to import the simple tpose into mixamo and redownload (skinned or not skinned is the same).
Then as you said you have to create a specific folder with just the prepared models and indicate as you said, only the folder name input and folder name output...then export with the settings you said.
Later I will put inside unreal engine...and try remap

Thanks for your realtime feedback, hope my guide will help... :)
