### ISSUE TITLE
When "Transfer Rotation" is selected, the animation glitches near the end

### ISSUE THREAD

**Issue by yutamago** [enziop/mixamo_converter#30]
A few keyframes near the end of every animation glitch out when "Transfer Rotation" is selected.

I'm using Blender 2.79b

**Comment by enziop** [comment]
could you please provide additional information on your problem?
did you use a ready rig from mixamo, one from the autorigger, or did you build the rig yourself?
does it only happen near the end or sometimes also at other times?
could you provide a small screencap of an example where it happens please

**Comment by enziop** [comment]
Please update to version 1.1.2 and try again, if your problem persists you can reopen the issue and provide some additional information.
