### ISSUE TITLE
Left Foot bone is upside down after conversion

### ISSUE THREAD

**Issue by yutamago** [enziop/mixamo_converter#31]
The left foot bone is upside down after conversion.
To fix it I have to reimport the mesh file, set the roll value of the left foot bone to -180 and export/overwrite the mesh file.

**Comment by enziop** [comment]
could you please provide additional information on your problem?
did you use a ready rig from mixamo, one from the autorigger, or did you build the rig yourself?
does it only happen for a ceartain animation or for all?
if you built it yourself, it seems you found the solution already, make sure the bone rolls are like in the mixamo rigs

**Comment by brandiqa** [comment]
Hey am having the same problem. Am using the xbot model

**Comment by sovietspaceship** [comment]
Unchecking Apply Rotation didn't work for me. Setting roll to 180 as suggested in the initial post worked, so I made a merge request to apply this as a workaround for the time being.
