### ISSUE TITLE
Random fast roations on a few animations

### ISSUE THREAD

**Issue by ShadeFlea** [enziop/mixamo_converter#32]
Example:
The Z axis portion of the Pelvis goes from 0 to -179 so it rotates almost 180 degrees when viewing in the Unreal Engine. This only happens in a few animations that have twisting flips or one that has a flip into a kick. The rest of the animations work great, even the forward flips and rolls, but these seem to constantly twist out.

I am using a FUSE autorigged character.

![capture](https://user-images.githubusercontent.com/39568717/40446952-9539fbec-5e96-11e8-946f-be31cf74b688.PNG)
![capture1](https://user-images.githubusercontent.com/39568717/40446953-954da0f2-5e96-11e8-96e0-b7d962eefabd.PNG)
![capture2](https://user-images.githubusercontent.com/39568717/40446955-9563b068-5e96-11e8-8ed3-2619a4895651.PNG)

Vid:

https://youtu.be/E8zwrnHPY0Q

**Comment by enziop** [comment]
I have a guess what could be the cause, could you provide an uncoverted source file where this happens?
does it also happen if you import the converted file to blender or only in Unreal?

**Comment by ShadeFlea** [comment]
Yes it also snaps like this in Blender.
https://www.dropbox.com/s/13tpl5uiyysd5a7/Drop%20Kick.fbx?dl=0

**Comment by enziop** [comment]
i can't reproduce that behavior with a flip in the middle of the animation on my end
are you using the latest version 1.1.0 ? you can see it in Blender->File->User Preferences->Addons->Mixamo Converter->Version

**Comment by ShadeFlea** [comment]
Yep. 1.1.0 is what I use. I use Blender 2.79 as well. Here is the process I
go by.

-Start Blender with default fresh install settings
-Open Mixamo tab
-Use setting as shown in screenshot above
-Click Batch Convert with no error
-Animation for this and a few others come out with random rotations.

Results are tested extensively in the UE4 and Blender.

Literally use it that simplistically. Again, most animations are superb.
Absolutely perfect. It is just this handful.

**Comment by enziop** [comment]
I tried with the animation you sent me and it didn't happen on that, but it looked like it already ran through the converter with some options disabled which didn't keep it untouched i think.

However, as i cant reproduce it, i made a hotfix for the part where i assume the problem.
i realeased version 1.1.1 where you can disable quaternion fix pre and post, which was done by default in 1.1.0
![image](https://user-images.githubusercontent.com/21155833/40562726-7fdfffee-6062-11e8-9cf7-3ee5a98325ba.png)

try converting a problematic animation with both disabled and reimport in blender to review it, if the problem persists, try with only pre enabled, and with only post enabled, to check if the problem still happens, as i don't have a file where the problem obviously happens, i can't track down the problem myself

**Comment by ShadeFlea** [comment]
Sounds good. I will try it right quick.

**Comment by ShadeFlea** [comment]
I just uploaded the newest file "after conversion" with USE Z and the Pre/Post Clean enabled:
https://www.dropbox.com/s/13tpl5uiyysd5a7/Drop%20Kick.fbx?dl=0

Still happens. I will upload the rest in a moment.

**Comment by ShadeFlea** [comment]
New File After Conversion
Both pre/post clean disabled. Problem is still there.
https://www.dropbox.com/s/qmrpkqjtl5l8o5h/Drop%20Kick%202.fbx?dl=0

**Comment by ShadeFlea** [comment]
Source File:
The source animation I am using:
https://www.dropbox.com/s/cco3v9vpa7if4p0/Drop%20Kick%20Source.fbx?dl=0

**Comment by ShadeFlea** [comment]
Finally a full on test with both source and converted animations flowing at the same time:
https://youtu.be/jn9YzKEHYXM

**Comment by enziop** [comment]
the source animation you provided seems to already have run through the conversion once already right it's not the state it came out of FUSE?
could you provide the real source?
If you don't like to share the mesh, you can import your original fbx to blender delete the mesh by selecting it with rightclick and delete it with Del. And before exporting, bind a dummy plane to it:
- Shift+A->Mesh->Plane
- Shift+Rightclick the Rig, so plane is selected and rig is active
- Ctrl + P -> Armature Deform with Empty Groups
then export it as fbx, standard settings should do it for our testing purpose

**Comment by enziop** [comment]
ok i just downloaded the Drop Kick animation from mixamo, i can finally reproduce the broken behavior. I am trying to fix it but can't promise it to be solved soon

**Comment by enziop** [comment]
Hey ShaderFlea,

I just released version 1.1.2 where the issue with 180 degree flips is fixed.
It was tested with the Drop Kick animation where it works fine now.
I'm happy to hear if your other animations are also working.
If your problem persists you can reopen the issue.

p.s.:
I don't have a patreon or anything similar, thank you. We are profiting of each other, your report also helps me to have a better mixamo converter for my own projects :)
