### ISSUE TITLE
Left leg rotation throughout animation

### ISSUE THREAD

**Issue by ShadeFlea** [enziop/mixamo_converter#33]
Vid:
https://youtu.be/BMacyJlq900

Same files as our previous issue. The hips are now converting flawlessly. Now it is the foot LOL.

**Comment by enziop** [comment]
which animation is that? i testet previous issue only with Drop Kick so far

**Comment by ShadeFlea** [comment]
It was the same animation just different angle.

**Comment by enziop** [comment]
I think i found the problem and fixed it with Version 1.1.3
tested with flip kick animation
if you encounter the problem on other animations, please reopen the issue and tell me the animation names where it happens
