### ISSUE TITLE
Converted Mixamo Animations on Retarget Skeleton not working

### ISSUE THREAD

**Issue by brandiqa** [enziop/mixamo_converter#36]
First, I would like to thank you very much for creating this Blender add-on. It really makes retargeting animations easy.

I've managed to successfully retarget a mixamo character to UE4 human rig. I've also retargeted several Third Person Animations to this new skeleton and I think they work perfectly. This are the main steps I followed:

- Downloaded xbot female in T-Pose
- Used the Convert SIngle option for converting rig
- Also clicked on Use Unreal Engine bone names
![Blender Mixamo Skeleton](https://snag.gy/lEVYmv.jpg)

- I imported this mesh skeleton, performed the retargeting process including retargeting the third person animations. Things worked perfectly up-to here:
![Unreal Mixamo Skeleton](https://snag.gy/VdDyij.jpg)

The next section is where am having difficulty. 

I did a batch conversion of the animations that I downloaded from Mixamo website. Just to confirm the conversion worked, I opened one of the output fbx animation files in Blender. Indeed, the bones were renamed as expected(including root) and the animation was working perfectly fine.

![Blender Animation Output for Walk](https://snag.gy/7X9t8M.jpg)

Unfortunately, when I import this converted animation to Unreal, I get this weird result that reminds me of the movie "The Thing":

![Unreal Imported Root Animation](https://snag.gy/C6obac.jpg)

Would you happen to know what I did wrong or if you have a solution for this. Thanks

**Comment by brandiqa** [comment]
I found a workaround I can use in the meantime. Doing the conversion one by one works properly. In the fbx export settings, I have selected:

- Armature only (under main tab)
- Baked animation, Key All bones (under animation tab)

Importing with the new skeleton works perfectly. Wish this can work in the Batch function

**Comment by enziop** [comment]
I think you should use batch convert for the T-Pose as well.
When batch converting, the importer uses automatic bone rotation in the fbx importer, when you converted your T-Pose with single conversion and importet it manually, you didn't use automatic bone rotation resulting in bones that have a different rest rotation then the ones in the batch converted animations, thus in the animations all bones are in 90° offset to one another resulting in "The Thing"

**Comment by brandiqa** [comment]
Thanks for the quick response. Unfortunately I did try to batch convert the t-pose at first and I got this error: 

```
Traceback (most recent call last):
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\__init__.py", line 369, in execute
    quaternion_clean_post=mixamo.quaternion_clean_post)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\mixamoconv.py", line 453, in batch_hip_to_root
    file_loader[file_ext](file.path)
  File "C:\Users\Mike\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\mixamoconv.py", line 425, in <lambda>
    use_prepost_rot=True),
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_fbx\__init__.py", line 234, in execute
    return import_fbx.load(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_fbx\import_fbx.py", line 2848, in load
    _(); del _
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_fbx\import_fbx.py", line 2846, in _
    blen_read_animations(fbx_tmpl_astack, fbx_tmpl_alayer, stacks, scene, settings.anim_offset)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\io_scene_fbx\import_fbx.py", line 676, in blen_read_animations
    if id_data.type == 'MESH' and id_data.parent and id_data.parent.type == 'ARMATURE':
AttributeError: 'NoneType' object has no attribute 'type'

location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189



location: <unknown location>:-1

```

**Comment by enziop** [comment]
Ok the problem seems to come from the option ignore leaf bones when importing,
i set it to true as a default but you can disable it
Enable advanced options, then in the batch convert box you can disable ignore leaf bones and the convert all your animations with that option disabled

i have to check again if it even makes sense to have it enabled as a default, it made sense in the project where i started developing the addon i think

**Comment by brandiqa** [comment]
Hey! Thanks for that solution. Disabling ignore leaf bone makes it possible to batch process the T-Pose mesh. Will make note of that next time I use the add-on.
