### ISSUE TITLE
Batch Conversion error

### ISSUE THREAD

**Issue by wudi34** [enziop/mixamo_converter#37]
In Blender 2.96 after click the Batch Conversion Button i get the following errror message, independ of the file-type of the mixamo character (or others), fbx or collada: 

Traceback (most recent call last):
  File "C:\Users\helmut\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\
addons\mixamo_converter-master\__init__.py", line 369, in execute
    quaternion_clean_post=mixamo.quaternion_clean_post)
  File "C:\Users\helmut\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\
addons\mixamo_converter-master\mixamoconv.py", line 406, in batch_hip_to_root
    for file in os.scandir(source_dir):
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\Users\\he
lmut\\Desktop\\FBX_Converter_examples\\Pepe_Mocap.FBX'
location: <unknown location>:-1

I follow rhe tutorial at  https://www.youtube.com/watch?v=D8nH2Yo9PT8  but with no Succes. What mean the error messages and how  I  to come forward ? Can you help me........

wudi34

**Comment by enziop** [comment]
Don't select a specific file when batch converting but only the folder.
it will then convert all files in that folder

**Comment by wudi34** [comment]
Thank's this is it !
