### ISSUE TITLE
location: <unknow location>:-1 when convert batch.

### ISSUE THREAD

**Issue by SimplestWay** [enziop/mixamo_converter#39]
at the end of my exception stack:
if id_date.type == 'MESH' ......
AttributeError: 'NoneType' object has no attribute 'type'
location: C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\bpy\ops.py:189
location: <unknow location>:-1

**Comment by SimplestWay** [comment]
With the same source .FBX file, using convert single works, but in batch mode, it failes.

**Comment by SimplestWay** [comment]
Solution:
Download mixamo animations one by one, a package animation is not supported by this plugin.

**Comment by enziop** [comment]
though it should support packages, i will check on that next week

**Comment by SimplestWay** [comment]
Hi, you are right, the problem may not be caused by the animation package, the problem should be that some models are not well supported.
Yesterday I downloaded a model called "paladin_j_nordstrom" and batch conversion still failed.
you can refer to the following procedure:
1. Download paladin_j_nordstrom model.
2. Open Blender -> Delete the cube in viewport -> open Mixamo menu.
3. Uncheck "Remove namespaces", Check "Use unreal bone names", "Fix bind", "ApplyRotation", "Apply Scale", set sacle to 100, check "Ignore leaf bones", "Automatic bone orientation", "Add Leaf bone", set input path and output path.
4. Press batch convert and you will see the error statck.

**Comment by enziop** [comment]
Ah i think i see the Problem, you shouldn't uncheck "Fix bind" and it should work, also with packs.
If you download a pack, it contains one file with the skinned mesh with rig in T-Pose and all the animations as files without a mesh, just the rig. As blenders FBX export can not export just a rig without skinned mesh i added the feature of skinning it to dummy geometry before exporting. That is wat "Fix bind" does.
Please check it for your case and close the bug again if it fixed it.

**Comment by SimplestWay** [comment]
Sorry, I have tried to check and unchecked the "Fix Bind" option, both of them failed to batch convert.
Actually, In my previous procedure, I Checked all stuff except "Remove namespaces" in step 4.
Some mesh like "Pelegrini_D_Knight" are successful converted use the same animation, no matter of downloading one by one or just using a anim pack. 
Maybe, you should  have a try to see if this type of model is causing such a problem.

![image](https://user-images.githubusercontent.com/26408256/44706585-ae5e3b80-aad4-11e8-9c3b-d1ce7866f9e8.png)
![image](https://user-images.githubusercontent.com/26408256/44706602-bc13c100-aad4-11e8-8386-9221d10db70b.png)

**Comment by enziop** [comment]
There is one more bug where you will get an Hips not Found Error when converting a pack, which contains the character in T-Pose with no animation. I am on that and it should be fixed no later than monday evening.

**Comment by SimplestWay** [comment]
Glad for hear that, thank you so much for spending time for this free plugin, this plugin helps me a lot and saved me a lot of time. Since English is not my first language, I am not able to find any suitable word to express my appreciation, Just say, Great work and keep going on 👍

**Comment by enziop** [comment]
ok, so the second bug with Hips not found should now be fixed, i will keep the issue open, as i still have to check if the default config of ignoring leaf bones still makes sense

**Comment by Iremodder** [comment]
I am having the same "location: <unknown location>:-1" error when batch converting mixamo animations.
I have a strong feeling adobe changed something on their online auto-rigger as it is now broken even on v1.0.9 of this converter (which functioned quite well). Updated to the latest version and the converter is having the same issue.

**Comment by enziop** [comment]
made ignore leaf bones default to false
