### ISSUE TITLE
'Hips not found'

### ISSUE THREAD

**Issue by PopeRigby** [enziop/mixamo_converter#40]
I know an issue was already opened for this but there was not a useful answer. When I click batch convert after specifying input and output location it gives me the 'Hips not found' error.

**Comment by enziop** [comment]
What Rig are you Using? Is it a Mixamo Rig?

**Comment by PopeRigby** [comment]
Yes. It's from Mixamo.

**Comment by PopeRigby** [comment]
One by one

**Comment by enziop** [comment]
Please update Mixamo Converter to Version 1.1.4 and check if your problem persists.
If a file now has no keyframes, they are added for conversion.
If you still get an error, please reopen the issue and report
