### ISSUE TITLE
Skeleton orientation problem. Bones pivot are offset

### ISSUE THREAD

**Issue by kendrickxy** [enziop/mixamo_converter#41]
Hi,
For about a month I tried to fix a problem with the bones but couldn't find any solution.

So here are some screenshots of the path I used to get this problem

![2018-09-07 01_38_51-window](https://user-images.githubusercontent.com/16179839/45206697-efe5a800-b285-11e8-8885-08cc8e4434d3.png)

First I download in Collada (Same with fbx. I used Collada because somethings I get a fail message with fbx)

![2018-09-07 01_43_21-window](https://user-images.githubusercontent.com/16179839/45206767-228fa080-b286-11e8-87dc-f08cc43b3b61.png)

Then I set everything right and remove Auto Bone Orientation

![2018-09-07 10_00_10-window](https://user-images.githubusercontent.com/16179839/45206884-8ade8200-b286-11e8-8f6a-52b5d2acb915.png)

![2018-09-07 10_00_22-window](https://user-images.githubusercontent.com/16179839/45206906-9d58bb80-b286-11e8-8202-99b154041357.png)

I import and link it to the UE4 skeleton

And here's the problem

![2018-09-07 10_03_29-window](https://user-images.githubusercontent.com/16179839/45206922-aba6d780-b286-11e8-922a-f48e40b9c903.png)

![2018-09-07 10_03_34-window](https://user-images.githubusercontent.com/16179839/45206926-ae093180-b286-11e8-93fd-45ad87f26da6.png)

![2018-09-07 10_03_49-window](https://user-images.githubusercontent.com/16179839/45206931-b3667c00-b286-11e8-85b0-951c282c26bf.png)

![2018-09-07 10_03_58-window](https://user-images.githubusercontent.com/16179839/45206933-b6616c80-b286-11e8-8ae1-7b16269c40cd.png)

Exactly the same result with Automatic Bone Orientation "on".

So now I don't know if it's my mistake or if it comes from the code.
Thanks!

**Comment by enziop** [comment]
So i did not yet have time to examine that issue.
For Clarification, this happens in both cases, if you use "Automatic Bone Orientation" and also if you don't use it?
I hope i will find the time to check on that sometime next week.

**Comment by PopeRigby** [comment]
Yes. Both cases

**Comment by kendrickxy** [comment]
Thanks for checking!
I'm not sure but after more inspection, I noticed that the bones rotation on the Mixamo skeleton (even before converting it) is different. It's like "mirrored" Compared to the UE4's one.
I'm not sure if it's something they recently changed in Mixamo.

**Comment by gnuton** [comment]
Hi there,
I haven't time for checking this issue either yet, but from the screenshots
I got suspicious about not using the reference T0 pose option, which should
be on from what I remember.
Are you very sure you import correctly your converted model in ue4?
Remember: First the t pose and then then animation. The animation must use
the skeleton of original t pose model.
Retargeting the animation to ue4 skeleton happens in a second stage.
There should be some videos on YouTube about it.

As for mixamo.. yes they may change their models from time to time and
introduce bugs.

Cheers
Antonio

**Comment by enziop** [comment]
What I assume happened, is theat and "unconverted rig" was imported into unreal, which had other bone orientations. Then "converted" animations were imported, which just rotated the bones along the wrong local axis in the unconverted rig.
