### ISSUE TITLE
Any plan to update for blender 2.80?

### ISSUE THREAD

**Issue by cgndev** [enziop/mixamo_converter#43]
.

**Comment by enziop** [comment]
I'am busy at the moment, updating to blender 2.8 might be done in a month or so.

**Comment by deathclonic** [comment]
I'll be rigging a lot of characters soon so I hope this gets updated. Thanks!

**Comment by enziop** [comment]
So there is a blender2.8 branch now. I didn't test all possible configurations yet. So there might still be bugs. When reporting please tell which version was used.
I plan to update the UI and the Docs a bit in the future and then merge to master.
