### ISSUE TITLE
location: <unknow location>:-1 when convert batch.

### ISSUE THREAD

**Issue by T2hDragon** [enziop/mixamo_converter#46]
![Capture](https://user-images.githubusercontent.com/54616162/63830396-b9141080-c974-11e9-9491-f598482fef12.PNG)
I have an issue whenever I try to batch convert an fbx file. It reads the path with double (//) instead of a single (/). Any ideas on how to fix it?

**Comment by enziop** [comment]
dont select a specific file but only the folder where the files are in, i will add a warning for that soon as this report comes quite often
