### ISSUE TITLE
it needs update for blender 2.8

### ISSUE THREAD

**Issue by MMahirAtar** [enziop/mixamo_converter#47]
in blender 2.8, there is no tool shelve and i can not use this plugin.

**Comment by enziop** [comment]
try 2.8 branch of the plugin and you will find it in the UI panel on the
right which you open with N

MMahirAtar <notifications@github.com> schrieb am Fr., 6. Sep. 2019, 00:53:

**Comment by tomm1e** [comment]
On Windows 64-bit, it won't install properly if any periods are in the addons directory name, I had to rename the folder inside the zip and install again, then it shows up in addons list, maybe rename the branch from blender2.8 to blender28.

**Comment by enziop** [comment]
@tomm1e thanks for the advice i renamed the branch
