### ISSUE TITLE
All Anims begin with a T pose in 2.8 version

### ISSUE THREAD

**Issue by Rob-bb** [enziop/mixamo_converter#48]
Hi,To be 100% fair this might not be a problem with this addon, I am a total novice with animations.
  
I have converted a mesh from Mixamo, and 3 animations, all the animations begin with a T-Pose in UE4.23 when I am previewing them.  Maybe this is normal, or a UE4.23 thing, or maybe it is how Mixamo exports them, but the Animations on Mixamo website don't begin with T Pose.

Apologies if this is not an issue with the addon.

**Comment by lmNt** [comment]
Hey @Rob-bb I am facing the same issue. As you have closed this issue, did you eventually find a solution?
