### ISSUE TITLE
Failed Conversion in Blender 2.79

### ISSUE THREAD

**Issue by DetoxxeGaming** [enziop/mixamo_converter#50]
I couldnt get the converter to work in Blender 2.8, so i reinstalled 2.79 and this is the error i get when I batch convert either a Fuse Character rigged in Mixamo or if I use a Mixamo Character.
![Capture](https://user-images.githubusercontent.com/23434915/64662560-e225ae00-d416-11e9-8b2f-823c3e3f62b0.PNG)

**Comment by enziop** [comment]
Sorry for the late reply.
Master branch is now upated und should work with 2.8.
It seems that you were not using the latest blender 2.79 build but some custom build with an old version of the FBX exporter.
