### ISSUE TITLE
TypeError: Converting py args to operator properties: : keyword "version" unrecognized

### ISSUE THREAD

**Issue by 980Mohid** [enziop/mixamo_converter#52]
I'm trying to convert a batch of animations from Mixamo and it's giving me this error.
Blender Version: 2.79.6

Traceback (most recent call last):
  File "C:\Users\MRN\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\__init__.py", line 366, in execute
    quaternion_clean_post=mixamo.quaternion_clean_post)
  File "C:\Users\MRN\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mixamo_converter-master\mixamoconv.py", line 519, in batch_hip_to_root
    mesh_smooth_type='FACE')
  File "F:\Stuff\Nafil's Stuff\Blender\blender-2.79.0-git.5a6f1fa5637-windows64\2.79\scripts\modules\bpy\ops.py", line 197, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "version" unrecognized

location: <unknown location>:-1

I was following this tutorial: https://www.youtube.com/watch?v=aTe_J2z0vLI&list=WL&index=47&t=0s

**Comment by enziop** [comment]
I think the fbx exporter changed a bit.
Are you using a blender Nightly build or experimental build?
For now you can try using 2.79b stable, it shoulb be working with this version.
Let me know if you got it working or still have trouble.

**Comment by 980Mohid** [comment]
> I think the fbx exporter changed a bit.
> Are you using a blender Nightly build or experimental build?
> For now you can try using 2.79b stable, it shoulb be working with this version.
> Let me know if you got it working or still have trouble.

I used a previously downloaded build. I think It was from when blender was transitioning into 2.80. I downloaded the 2.79b and it's working perfectly now. Thanks man you've saved my ass. The support you're dishing out on this free add on is amazing. Any plans for 2.8+ blender builds?

**Comment by enziop** [comment]
Thank you.
There is a 2.8 branch already which you can download. I haven't yet tested it with 2.82.

**Comment by 980Mohid** [comment]
> Thank you.
> There is a 2.8 branch already which you can download. I haven't yet tested it with 2.82.

Oh, there is a 2.8 branch? I didn't know. Thanks for letting me know.
