### ISSUE TITLE
2.81a error

### ISSUE THREAD

**Issue by crossmr** [enziop/mixamo_converter#54]
I can't enable this under 2.81a. Using enziop/mixamo_converter/tree/blender28

When I do I get an error, screenshot attached. 
![error](https://user-images.githubusercontent.com/8927231/70383501-1840e280-19b2-11ea-8885-07f2e53979a8.jpg)

**Comment by station437** [comment]
the same error, 2.81.16

**Comment by enziop** [comment]
resolved by #60
