### ISSUE TITLE
2.80 Conversion Error

### ISSUE THREAD

**Issue by crossmr** [enziop/mixamo_converter#55]
Since the plugin doesn't work in 2.81a, I fired up my 2.80 copy of blender and tried to convert an animation. 

I get the following error with the selected settings: 

![error2](https://user-images.githubusercontent.com/8927231/70383682-38be6c00-19b5-11ea-9247-3fb7efef28ad.jpg)

**Comment by enziop** [comment]
sorry for the late reply, i cant reproduce the error, which rig did you use as input?
is this issue still valid?

**Comment by crossmr** [comment]
Sorry, this happened 3 months ago, I can't really recall.

**Comment by enziop** [comment]
this should be fixed now, kneefix should not be executed if set to (0, 0, 0)
