### ISSUE TITLE
"Error, not all files could be converted" Batch Converter

### ISSUE THREAD

**Issue by Iamawesome12345** [enziop/mixamo_converter#56]
Am I missing something here? Is there a certain naming convention the anims need to have for it to work?

**Comment by Iamawesome12345** [comment]
Also I see on the home page it says something about batch convert only working on original mixamo rigs, does this mean I cant do custom characters?

**Comment by enziop** [comment]
Hi, sorry for the late reply.

- I updated some of the file input handling which might fix some problems.
- The anims don't need to follow any naming convention.
- But if you want to use the "Use Unreal Engine Bone Names" feature your rig needs to follows mixamos bone naming convention.
- If you only need root motion conversion and not name remapping or experimental features like foot bone workaround you can also use any rig you like. But if the Hip bone of your character is not named "Hips" or "Pelvis" you have to specify the name in the  Hip Name field under advanced options.

please let me know if the issue persists
