### ISSUE TITLE
Not working with 2.80

### ISSUE THREAD

**Issue by ajeets1978** [enziop/mixamo_converter#59]
I can see the plugin in Preference -> Add Ons, with a warning upgrade to 2.8x required, I am using 2.80 only ?

I don't see Mixamo anywhere in my 3D views. Please suggest.

**Comment by Gumbee** [comment]
Make sure you download and install the zip for the branch blender28

**Comment by enziop** [comment]
duplicate of #54
now masterbranch is 2.8 version and should work again
