### ISSUE TITLE
Add On not Working With Blender 2.81a

### ISSUE THREAD

**Issue by CQH-2020** [enziop/mixamo_converter#62]
I have tried to use all 4 of the branches and none of them worked.

The master, ajugglerstale, and develop branches all say to update to 2.8 (which I am already using). 

The blender28 branch does not tell me to update, however, it does throw an error that keeps me from enabling it.

The error is:
```
Exception in module register(): /Users/dendenden/Library/Application Support/Blender/2.81/scripts/addons/mixamo_converter-blender28/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.81/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
  File "/Users/dendenden/Library/Application Support/Blender/2.81/scripts/addons/mixamo_converter-blender28/__init__.py", line 499, in register
    bpy.utils.register_class(cls)
TypeError: expected Operator, OBJECT_OT_RemoveNamespace class "description" attribute to be a static/class method, not a str
```

 I hope this addon is still being supported.

**Comment by Gumbee** [comment]
there is a pull request which fixes the add on for Blender 2.81a. It hasn't been merged yet, but you can use that branch if you need it to work with Blender 2.81a

**Comment by guidocir** [comment]
Hello, the issue is blocking, when will it be fixed?
Many thanks,
Guido

**Comment by enziop** [comment]
duplicate of #54
now masterbranch is 2.8 version and should work again
