### ISSUE TITLE
First Frame is a T-Pose

### ISSUE THREAD

**Issue by Ultrajungleboy** [enziop/mixamo_converter#66]
while using blender 2.80 I noticed that the first frame of every animation original mixamo FBX file I imported had a default Tpose(even though the keyframe is not of a t pose) until the animation keyframe timeline Is accessed, this resulted in every animation in the batch output folder with a t-pose for the first frame until the next key frame was accessed however I found an annoying but usable workaround. When the timeline is clicked on the model automatically updates to the correct keyframe pose, this leads me to believe that an easy workaround for this problem could be starting to access the keyframes at keyframe 0 rather than 1, but not converting any of the keyframe 0 data, if this is not a viable solution then you could always record keyframe one twice, I would do it myself but I'm too lazy to learn python to do so lol.

However, I believe updating to 2.82 fixes this as so far it has worked for me when batch converting

**Comment by xtremertx** [comment]
Hi, can you make some screenshots when converting in batch and post here?
I was trying multiple settings and converted animations look weird (https://github.com/enziop/mixamo_converter/issues/65).

**Comment by Ultrajungleboy** [comment]
There should be a root bone offset setting have you tried that and have you tried updating blender? Also are they the fbx itself or is it only after it’s been imported somewhere such as unity or unreal? Also do you have other animation layers that could be interfering?

**Comment by xtremertx** [comment]
Using FBX directly from mixamo without skeletal mesh, only animation (i have also tries with skeletal mesh & Fix Bind option). No anim. layers in UE4. 

Which option are you refering to "root bone offset"? Will try to open that in blender and use latest blender too.

**Comment by enziop** [comment]
@xtremertx i recently heard that some fbx files from mixamo contain two animations, one with just a t-pose and one with the actual animation. Seems like the converter is selecting the wrong one in those cases.
Can you tell me for which animation(s) this happens?
You can tell me the exact animation by also giving me the description which shows up when hovering over the name.
![image](https://user-images.githubusercontent.com/21155833/79555527-0548c800-80a0-11ea-901e-0b8267c6dfe4.png)

**Comment by Casalis** [comment]
I have the same issue but I have found it can be solved by first importing the FBX file into Blender and just exporting it then using that new FBX in the conversion.  😜 

Maybe there is some kind of FBX version problem. For me, it happens with every animation I've tried so far but if you want a specific example:
Falling Idle
Description: mid-air falling idle

If you cant re-create it I can provide an example FBX file.
Hope this helps!

**Comment by enziop** [comment]
That's weird. I Just testet the Animation you named with
- Mixamo Female Bot model
- own model using Mixamos Autorigger
- prerigged own model
Converted with Batch Convert. Checked by importing the results back to Blender aswell as importing them in Unreal. For none of the cases i got a T-Pose at the first Frame.

Which blender version are you using? I suspect, that importing the FBX by script didn't update the first frame animation Pose in 2.80 correctly. I was using 2.82a for my tests.

**Comment by Casalis** [comment]
So I just downloaded blender 2.82a and there are now no problems.
It's defiantly related to version 2.8 then. Weird
Thanks a lot! 👍

**Comment by enziop** [comment]
Happy to hear it's working now. Im closing the Issue now.
