### ISSUE TITLE
Cant find the addon menus in the 3d view.....

### ISSUE THREAD

**Issue by AviranAbady** [enziop/mixamo_converter#70]
in Blender 2.8.0 / Blebder 2.8.2a, after installing the add on, it does not appear anywhere in the blender UI, where is it located?

Trying using blender 2.78, you get an error when installing the add on, seems like a python compatibility issue.

@enziop @sovietspaceship

**Comment by xtremertx** [comment]
https://blender.stackexchange.com/questions/1688/installing-an-addon#1689

**Comment by AviranAbady** [comment]
@xtremertx On blender 2.78, install fails due to syntax errors, the `MixamoPropertyGroup` properties seems to be causing that.

In blender 2.8+, the installation seems to work well, the add on is activated.
see [Screenshot](https://i.imgur.com/JYqfQUr.png)
That said, i cant locate any `Mixamo Converter` UI in my 3D View, or anywhere in the blender UI.

Not sure if im missing something or is it just not working in 2.8.0+

**Comment by sovietspaceship** [comment]
Have you tried using the 2.7 branch? https://github.com/enziop/mixamo_converter/tree/blender27

**Comment by AviranAbady** [comment]
thanks, had to move some panels and it poped into view.
