### ISSUE TITLE
Toe bones issue

### ISSUE THREAD

**Issue by KeyC0de** [enziop/mixamo_converter#71]
I have an issue with the toe bones, stretching awkardly and quite unnaturally. Take a look:
![anim2](https://user-images.githubusercontent.com/17159000/81846920-8ab67f80-955b-11ea-8e30-1142a4ba150f.jpg)

These are the options I use:
![mixamo_converter_blender_settings](https://user-images.githubusercontent.com/17159000/81848897-71fb9900-955e-11ea-9ac3-71ed8a717b7a.jpg)

But I have tried many combinations with no good outcome. This happens to all the mixamo anims I tried.
Why is this happening and how can I fix it?

**Comment by sovietspaceship** [comment]
Try Experimental Options -> Foot Bones Workaround. Some models have those bones twisted by 180 degrees, the option flips them back.

**Comment by KeyC0de** [comment]
I did try this already to no avail.

**Comment by KeyC0de** [comment]
Strange. I downloaded the animations again and now they worked (with the options I showed in the image).. : |
