### ISSUE TITLE
Convert single does not work 

### ISSUE THREAD

**Issue by gameunite** [enziop/mixamo_converter#73]
I'm trying to do it one by one. Batch convert works perfectly but I have issue when I import the fbx and doing it by single conversion. Here's the steps on how I did it.

1. Import Character in blender
2. Run "Use Unreal Engine bone names"
3. Press Convert Single using these settings
![image](https://user-images.githubusercontent.com/31096909/83947962-e3242880-a84c-11ea-8e16-50570c59edff.png)
4. Export as FBX using these settings
![image](https://user-images.githubusercontent.com/31096909/83948002-1b2b6b80-a84d-11ea-85f7-5833bc8057a4.png)
5. Do 1-4 now with the animation fbx
6. Import converted fbx files in UE 4.25
7. Animation assets doesn't show anything.
![image](https://user-images.githubusercontent.com/31096909/83948212-5d08e180-a84e-11ea-887a-85decb8eae6e.png)

It works perfectly fine with batch convert though. Did I miss any steps on single convert?

Now with batch convert, I didn't have those LeftHand bones and it's working perfectly.

![image](https://user-images.githubusercontent.com/31096909/83948399-a148b180-a84f-11ea-9230-b3610826b6ac.png)

**Comment by enziop** [comment]
Do you get the animation when reimporting the fbx into a new blender session?

**Comment by gameunite** [comment]
Sorry I forgot to reply. Yup I have to create a new blender session for it to not work correctly. I can close this now. Thank you!
