### ISSUE TITLE
Mixamo Convertor not shoving up in Blender Workspace

### ISSUE THREAD

**Issue by ShantanuShinde** [enziop/mixamo_converter#75]
I downloaded the .zip file. Went to preferences, selected install and then went to the zip file. Then I enabled the add on. But it is not showing up in the workspace. Also, I think my Blender is updated version, hence the workspace looks different from the tutorials
![Here, cannot see the Mixamo options](https://user-images.githubusercontent.com/32991453/87111718-ab633300-c287-11ea-95b1-88df45f8d5f9.png)
![I enabled the add on here](https://user-images.githubusercontent.com/32991453/87111728-b0c07d80-c287-11ea-8fc6-c16e9f4bd0cc.png)

**Comment by enziop** [comment]
You open up the right panel (UI Panel) by clicking the small arrow on the right side of the 3D view or simply by pressing T.

**Comment by Pfoxinator** [comment]
I'm having the same problem, I see YouTube videos where this Mixamo plugin works and the UI looks different.  Pressing T just makes the little panel on the left with the selection / moving / scaling options expand or collapse.  There is not a Mixamo plugin in that list and I can't find it in any other toolbar or menu.

**Comment by enziop** [comment]
I'm sorry, i mean you can open it by Pressing N not T. I just updated the Readme.
