### ISSUE TITLE
wont let me convert on UE4 4.25.2..

### ISSUE THREAD

**Issue by ADHDeveloper** [enziop/mixamo_converter#76]
I'm pretty sure I'm doing it correctly and I'm starting to question if this software works. this is the error message I receive.
![ERROR](https://user-images.githubusercontent.com/68732040/88388692-a4095280-cd7a-11ea-9e71-e2c74564a9e3.png)

**Comment by enziop** [comment]
Make sure you have enabled the FBX importer addon. It should be enabled by default.
Open Edit -> Preferences -> Addons -> search for FBX enable the 'Import-Export: FBX format' addon.
Let me know if this doesn't fix it.
