### ISSUE TITLE
Probleme pour root mon personnage 

### ISSUE THREAD

**Issue by Mathew3585** [enziop/mixamo_converter#77]
Bonjour j ai un probleme j ai utiler le ybot de mixamo pour le root et ca me donne et je n ai rien dans mob dossier out c'est normal?
![Blender 26_07_2020 13_03_27](https://user-images.githubusercontent.com/68810417/88477505-da90ca00-cf40-11ea-8a93-052cde014ba5.png)

**Comment by Mathew3585** [comment]
Ca fait 2 semain que j'essaye a ca marhe pas pourquoi?

**Comment by enziop** [comment]
I'm sorry i don't speak french. Are there any other FBX files in the source folder, that are not mixamo animations?

**Comment by SanchDev** [comment]
Salut Mathew, tente de télécharger la version 2.81 de Blender et recommence, j'ai aussi galéré comme toi j'ai l'impression c'est qu'une question de versions.

**Comment by enziop** [comment]
I guess this was a interface language specific issue, from version 1.2.3 on the addon is now language independent.
