### ISSUE TITLE
Use lowlevel api instead of operators for Object and Constraint Creation

### ISSUE THREAD

**Issue by Sherwin258256** [enziop/mixamo_converter#78]
![image](https://user-images.githubusercontent.com/69609937/90080866-5743e680-dd3e-11ea-94e2-3e3fbac8262f.png)
i tried many times ....help
![V0~}QC`44 DDDM2NIP53%ID](https://user-images.githubusercontent.com/69609937/90081198-48a9ff00-dd3f-11ea-88a7-a72711794e97.png)
The oUT folder is empty 
Is there something wrong with my file？

**Comment by enziop** [comment]
Could you try again and show the output of the console?
You can open console via Window->Toggle System Console
![image](https://user-images.githubusercontent.com/21155833/92485365-22b33580-f1eb-11ea-8d26-6052aa478359.png)

**Comment by pharaf** [comment]
Hello i have the same error! I'am using blender 2.90! Below is the output of the console! 
![Capture d’écran 2020-09-12 225219](https://user-images.githubusercontent.com/30377417/93004801-dcdbd180-f54a-11ea-9ef5-cda563faf3f2.png)

**Comment by pharaf** [comment]
> Hello i have the same error! I'am using blender 2.90! Below is the output of the console!
> ![Capture d’écran 2020-09-12 225219](https://user-images.githubusercontent.com/30377417/93004801-dcdbd180-f54a-11ea-9ef5-cda563faf3f2.png)

It seems like the error is due to blender 2.9 i think the plugin is not compatible with that version. After installing blender 2.81 the conversion worked!

**Comment by SanchDev** [comment]
I used the 2.81 , before the 2.9, even the 2.83.3 , but with the **2.81 it works perfectly (for Batch)** !

**Comment by enziop** [comment]
this actually had to do with language setting dependence.
It is now Fixed in version 1.2.3
Constraints and Objects are now not constructed with operators but with the lowlevel way
