### ISSUE TITLE
Decode error

### ISSUE THREAD

**Issue by Pitr2** [enziop/mixamo_converter#82]
Hello, I cannot use your plugin, because while trying to "Convert single" i get the following exception:

> Traceback (most recent call last):
>   File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\mixamo_converter-master\__init__.py", line 234, in execute
>     hipname = mixamo.hipname.decode('UTF-8'),
> AttributeError: 'str' object has no attribute 'decode'
> 
> location: <unknown location>:-1

What can I do?
Thank you

**Comment by lospe85** [comment]
I have the same issue. Running Blender 2.79

**Comment by enziop** [comment]
thanks for the report fixed now in both blender28 (master) and blender27 branch
