### ISSUE TITLE
Not working with Different Language as Constraints are Named differently and accesed by name

### ISSUE THREAD

**Issue by IFlickerz** [enziop/mixamo_converter#85]
**Resume:**

Hi, I'm following this tutorial (https://www.youtube.com/watch?v=vW5dAvuOw9c) step-by-step to convert the same character of his, but it keeps generating errors in the console and doesn't convert the character. The error is: '**ERROR hip_to_root raised 'bpy_prop_collection[key]: key "Copy Location" not found' when processing _eve.fbx_**' and is shown after the 'using z' log output.

**Test case:**

Here's the setup that I'm using (Version 28):

![image](https://user-images.githubusercontent.com/44907434/108034751-c0215980-7014-11eb-91a9-baaceefbec83.png)

And that's the output:

![image](https://user-images.githubusercontent.com/44907434/108034741-b992e200-7014-11eb-922c-dc509748ad8b.png)

Many thanks.

**Comment by IFlickerz** [comment]
[FIXED]

Change the Blender version to 2.80 that will work fine, apparently there's no support to newer versions yet

**Comment by enziop** [comment]
This is actually not dependant on the version of Blender. I tested 2.83 through 2.92 and all version work.
But i just found out, that it depends on your language setting, i have to invasigate this, this should definitely not happen.

**Comment by enziop** [comment]
fixed in version 1.2.3
the addon should now be fully language independent
