### ISSUE TITLE
Not all files could be converted

### ISSUE THREAD

**Issue by james0208331** [enziop/mixamo_converter#86]
Hello sorry for bother you but I had an issue with this mixamo converted, it says "not all files could be converted, look in console for more information. I tried witth a lot of meshes and also I tried only with the T pose and mesh but it doesnt work, I will be so grateful if you can help me with this, The best regards from me!

**Comment by fyleos** [comment]
To solve this point, I've switch my interface in English (I've the same error when Blender is in French)

**Comment by enziop** [comment]
if this was also the case for the original problem from @james0208331 it is now fixed in version 1.2.3 as it is now fully language independent
