### ISSUE TITLE
how does it works just in blender? 

### ISSUE THREAD

**Issue by giutech** [enziop/mixamo_converter#88]
Hello, I downloaded the add-on, I would like to use it just in blender (is possible?) If I understood it should give me a more detailed ik rig?? I'm wrong? Could you please make a tutorial just for the people who are using just blender? 
Thank you very much
Jules 

giutech@gmail.com

**Comment by brkeejp** [comment]
dude just import mixamo anim/skel and go a head to side panel and select mixamo tab. Also not for ik/fk exporting as root anim from mixamo export. But you can use Mixamo's blender plugin for ik

**Comment by enziop** [comment]
This addon is not meant to give you an IK rig. Its sole purpose is to create a root bone on the ground, and bake parts of the gips motion to that root bone instead of being on the hip bone, for supporting root motion in Unreal Engine.
