### ISSUE TITLE
Batch Convert not working

### ISSUE THREAD

**Issue by KingOKarma** [enziop/mixamo_converter#91]
I've been trying to get Batch Convert to work by using a lot of different methods, but it constnatly says 
`Error: Not all files could be converted, look in console for more information`

With nothing actaully appearing in the console to give any info, So I'm at a loss, the files work completely fine for solo conversion 
(as a side note when I press Batch Convert it only converts the top file of the Input folder and imports it to the Blender Viewport but does not export to the output folder specified...)

So I'm lost and confused here as to what reason these files could not be converting.

I'm not sure if you guys even still look at this repo, but I hope you do as I can't seem to find any other method of getting a root bone onto a mixamo model <3

**Comment by Defunctionalize** [comment]
this issue seems to be related to Blender 3.x changing the way it passes arguments to plugins.

When performing conversion, the following error is printed to console:

`ERROR hip_to_root raised Converting py args to operator properties:  NLA_OT_bake.frame_start expected an int type, not float when processing mutant.fbx
`
a float is somehow being passed as the start frame..

**Comment by mrChlis** [comment]
Have same issue. Any solutions?

**Comment by mrChlis** [comment]
> Have same issue. Any solutions?

My solution - install Blender **2.81**

**Comment by anasanas0** [comment]
The same error occurred to me in the version of Blender, use Blender 3.0.1 and the addon will work without problems

**Comment by Copperplate** [comment]
> fixed https://github.com/brkeejp/mixamo_converter

Thank you so much, Berk! This is fantastic!! No more "NLA_OT_bake.frame_start expected an int type, not float" error in Blender 3.3 beta when trying to use the "Convert Single" option on an existing armature.

Previous error before fix:

![image](https://user-images.githubusercontent.com/16230743/183975397-c87a0d3a-992e-439c-8ef3-e04e4492090b.png)

**Comment by enziop** [comment]
The addon was only working in blender 2.8x before, but it should now also work in current blender versions.
fixed by merging #93
