### ISSUE TITLE
I get error after press "Batch Convert" button

### ISSUE THREAD

**Issue by cynerboy** [enziop/mixamo_converter#94]
In console blender I get this error:
ERROR hip_to_root raised Converting py args to operator properties:  NLA_OT_bake.frame_start expected an int type, not float when processing T-Pose.fbx

Thanks in advance

**Comment by chrismbuthia** [comment]
i am getting the same issue

**Comment by enziop** [comment]
The addon was only working in blender 2.8x before, but it should now also work in current blender versions.
fixed by merging #93
